create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  channel text not null check (channel in ('league-feed','trade-talk','memes')),
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  content text not null default '',
  media_url text,
  parent_id uuid references public.messages(id) on delete set null,
  created_at timestamptz not null default now(),
  check (channel <> 'memes' or media_url is not null)
);

create table if not exists public.message_reactions (
  message_id uuid not null references public.messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null,
  display_name text not null,
  created_at timestamptz not null default now(),
  primary key (message_id,user_id,emoji)
);

create table if not exists public.trade_block_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_team_id text,
  author_team_name text,
  player_name text not null check (char_length(player_name) between 1 and 100),
  position text,
  nfl_team text,
  note text check (char_length(coalesce(note, '')) <= 500),
  status text not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now()
);

create table if not exists public.trade_interests (
  trade_item_id bigint not null references public.trade_block_items(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (trade_item_id,user_id)
);

create table if not exists public.power_ranking_comments (
  id bigint generated by default as identity primary key,
  ranking_key text not null check (char_length(ranking_key) between 1 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  author_avatar text,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.power_ranking_reactions (
  id bigint generated by default as identity primary key,
  ranking_key text not null check (char_length(ranking_key) between 1 and 100),
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null check (emoji in ('👍','❤️','😂','🔥','🏈','👀')),
  display_name text not null,
  created_at timestamptz not null default now(),
  unique (ranking_key,user_id,emoji)
);

alter table public.power_ranking_reactions add column if not exists display_name text not null default 'League member';
alter table public.power_ranking_reactions drop constraint if exists power_ranking_reactions_emoji_check;
alter table public.power_ranking_reactions drop constraint if exists power_ranking_reactions_emoji_length_check;
alter table public.power_ranking_reactions add constraint power_ranking_reactions_emoji_length_check check (char_length(emoji) between 1 and 32);

create index if not exists power_ranking_comments_key_idx on public.power_ranking_comments(ranking_key,created_at);
create index if not exists power_ranking_reactions_key_idx on public.power_ranking_reactions(ranking_key);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.trade_block_items enable row level security;
alter table public.trade_interests enable row level security;
alter table public.power_ranking_comments enable row level security;
alter table public.power_ranking_reactions enable row level security;

drop policy if exists "gmail profiles" on public.profiles;
create policy "gmail profiles" on public.profiles for all to authenticated
using ((auth.jwt()->>'email') like '%@gmail.com') with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail reads messages" on public.messages;
create policy "gmail reads messages" on public.messages for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates messages" on public.messages;
create policy "gmail creates messages" on public.messages for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "owners delete messages" on public.messages;
create policy "owners delete messages" on public.messages for delete to authenticated using (user_id=auth.uid());
drop policy if exists "gmail reads reactions" on public.message_reactions;
create policy "gmail reads reactions" on public.message_reactions for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates reactions" on public.message_reactions;
create policy "gmail creates reactions" on public.message_reactions for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "owners delete reactions" on public.message_reactions;
create policy "owners delete reactions" on public.message_reactions for delete to authenticated using (user_id=auth.uid());

drop policy if exists "gmail reads trade block" on public.trade_block_items;
create policy "gmail reads trade block" on public.trade_block_items for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates trade block" on public.trade_block_items;
create policy "gmail creates trade block" on public.trade_block_items for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "owners update trade block" on public.trade_block_items;
create policy "owners update trade block" on public.trade_block_items for update to authenticated using (user_id=auth.uid()) with check (user_id=auth.uid());
drop policy if exists "gmail reads trade interests" on public.trade_interests;
create policy "gmail reads trade interests" on public.trade_interests for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates trade interests" on public.trade_interests;
create policy "gmail creates trade interests" on public.trade_interests for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "owners delete trade interests" on public.trade_interests;
create policy "owners delete trade interests" on public.trade_interests for delete to authenticated using (user_id=auth.uid());

drop policy if exists "gmail reads ranking comments" on public.power_ranking_comments;
create policy "gmail reads ranking comments" on public.power_ranking_comments for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates ranking comments" on public.power_ranking_comments;
create policy "gmail creates ranking comments" on public.power_ranking_comments for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "authors delete ranking comments" on public.power_ranking_comments;
create policy "authors delete ranking comments" on public.power_ranking_comments for delete to authenticated using (user_id=auth.uid());
drop policy if exists "gmail reads ranking reactions" on public.power_ranking_reactions;
create policy "gmail reads ranking reactions" on public.power_ranking_reactions for select to authenticated using ((auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "gmail creates ranking reactions" on public.power_ranking_reactions;
create policy "gmail creates ranking reactions" on public.power_ranking_reactions for insert to authenticated with check (user_id=auth.uid() and (auth.jwt()->>'email') like '%@gmail.com');
drop policy if exists "authors delete ranking reactions" on public.power_ranking_reactions;
create policy "authors delete ranking reactions" on public.power_ranking_reactions for delete to authenticated using (user_id=auth.uid());

grant select,insert,update on public.trade_block_items to authenticated;
grant select,insert,delete on public.trade_interests to authenticated;
grant select,insert,delete on public.power_ranking_comments to authenticated;
grant select,insert,delete on public.power_ranking_reactions to authenticated;
grant usage,select on all sequences in schema public to authenticated;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('message-media','message-media',true,6291456,array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do nothing;

drop policy if exists "public message media" on storage.objects;
create policy "public message media" on storage.objects for select using (bucket_id='message-media');
drop policy if exists "gmail uploads message media" on storage.objects;
create policy "gmail uploads message media" on storage.objects for insert to authenticated
with check (bucket_id='message-media' and (storage.foldername(name))[1]=auth.uid()::text and (auth.jwt()->>'email') like '%@gmail.com');

notify pgrst, 'reload schema';
